version: '3.9'

services:

  nodejs:
    container_name: nodejs
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:16.3
    env_file:
      - .dev.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always